apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-metallb.yaml
  - 02-configMap.yaml

commonLabels:
  author: anibal-aguila

patchesStrategicMerge:
  - patchConfigMap.yaml